// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Westmarchestool.Infrastructure.Data;

#nullable disable

namespace Westmarchestool.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251108180158_AddPlayerDrivenMapping")]
    partial class AddPlayerDrivenMapping
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Westmarchestool.Core.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ancestry")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Background")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CopperPieces")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<int>("GoldPieces")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PlatinumPieces")
                        .HasColumnType("int");

                    b.Property<string>("PortraitUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SilverPieces")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.CharacterHistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ChangeType")
                        .HasColumnType("int");

                    b.Property<int?>("ChangedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OldValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterHistory");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.CharacterInventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AcquiredDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemDataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("ShopTransactionId")
                        .HasColumnType("int");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterInventory");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.CharacterJsonData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ImportedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("JsonContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.ToTable("CharacterJsonData");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Full system access",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Game Master access",
                            Name = "GM"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Player access",
                            Name = "Player"
                        });
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExperienceReward")
                        .HasColumnType("int");

                    b.Property<int>("GameMasterUserId")
                        .HasColumnType("int");

                    b.Property<int>("GoldReward")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameMasterUserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.SessionAttendee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attended")
                        .HasColumnType("bit");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("ExperienceReceived")
                        .HasColumnType("int");

                    b.Property<int>("GoldReceived")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RewardsDistributedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SignedUpDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("SessionId");

                    b.ToTable("SessionAttendees");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Westmarchestool.HexMap.Entities.ConflictVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConflictId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<bool>("VoteForNew")
                        .HasColumnType("bit");

                    b.Property<DateTime>("VotedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ConflictId", "PlayerId")
                        .IsUnique();

                    b.ToTable("ConflictVotes");
                });

            modelBuilder.Entity("Westmarchestool.HexMap.Entities.Expedition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("LastKnownQ")
                        .HasColumnType("int");

                    b.Property<int?>("LastKnownR")
                        .HasColumnType("int");

                    b.Property<int>("LeaderPlayerId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReturnTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("StartQ")
                        .HasColumnType("int");

                    b.Property<int>("StartR")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("LeaderPlayerId");

                    b.HasIndex("Status");

                    b.ToTable("Expeditions");
                });

            modelBuilder.Entity("Westmarchestool.HexMap.Entities.ExpeditionHex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActualQ")
                        .HasColumnType("int");

                    b.Property<int>("ActualR")
                        .HasColumnType("int");

                    b.Property<int>("ExpeditionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExploredTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAccurate")
                        .HasColumnType("bit");

                    b.Property<int>("Q")
                        .HasColumnType("int");

                    b.Property<int>("R")
                        .HasColumnType("int");

                    b.Property<string>("TerrainType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ExpeditionId", "Q", "R");

                    b.ToTable("ExpeditionHexes");
                });

            modelBuilder.Entity("Westmarchestool.HexMap.Entities.ExpeditionMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("ExpeditionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ExpeditionId");

                    b.HasIndex("PlayerId");

                    b.ToTable("ExpeditionMembers");
                });

            modelBuilder.Entity("Westmarchestool.HexMap.Entities.HexTile", b =>
                {
                    b.Property<int>("Q")
                        .HasColumnType("int");

                    b.Property<int>("R")
                        .HasColumnType("int");

                    b.Property<int?>("ActualQ")
                        .HasColumnType("int");

                    b.Property<int?>("ActualR")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DiscoveredByExpeditionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DiscoveredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GMNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasPOI")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAccurate")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExploredByGM")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnTownMap")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("POIData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TerrainType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Q", "R");

                    b.HasIndex("DiscoveredByExpeditionId");

                    b.HasIndex("IsExploredByGM");

                    b.HasIndex("IsOnTownMap");

                    b.HasIndex("TerrainType");

                    b.ToTable("HexTiles");
                });

            modelBuilder.Entity("Westmarchestool.HexMap.Entities.MapConflict", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExistingSubmitterId")
                        .HasColumnType("int");

                    b.Property<string>("ExistingTerrainType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NewSubmitterId")
                        .HasColumnType("int");

                    b.Property<string>("NewTerrainType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Q")
                        .HasColumnType("int");

                    b.Property<int>("R")
                        .HasColumnType("int");

                    b.Property<string>("Resolution")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResolvedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExistingSubmitterId");

                    b.HasIndex("NewSubmitterId");

                    b.HasIndex("Status");

                    b.HasIndex("SubmissionId");

                    b.HasIndex("Q", "R");

                    b.ToTable("MapConflicts");
                });

            modelBuilder.Entity("Westmarchestool.HexMap.Entities.TownMapSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExpeditionId")
                        .HasColumnType("int");

                    b.Property<int>("HexesAccepted")
                        .HasColumnType("int");

                    b.Property<int>("HexesConflicted")
                        .HasColumnType("int");

                    b.Property<int>("HexesSubmitted")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubmittedByPlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpeditionId");

                    b.HasIndex("Status");

                    b.HasIndex("SubmittedByPlayerId");

                    b.ToTable("TownMapSubmissions");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.Character", b =>
                {
                    b.HasOne("Westmarchestool.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.CharacterHistoryEntry", b =>
                {
                    b.HasOne("Westmarchestool.Core.Entities.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId");

                    b.HasOne("Westmarchestool.Core.Entities.Character", "Character")
                        .WithMany("History")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.CharacterInventoryItem", b =>
                {
                    b.HasOne("Westmarchestool.Core.Entities.Character", "Character")
                        .WithMany("Inventory")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.CharacterJsonData", b =>
                {
                    b.HasOne("Westmarchestool.Core.Entities.Character", "Character")
                        .WithOne("JsonData")
                        .HasForeignKey("Westmarchestool.Core.Entities.CharacterJsonData", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.Session", b =>
                {
                    b.HasOne("Westmarchestool.Core.Entities.User", "GameMaster")
                        .WithMany()
                        .HasForeignKey("GameMasterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameMaster");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.SessionAttendee", b =>
                {
                    b.HasOne("Westmarchestool.Core.Entities.Character", "Character")
                        .WithMany("SessionAttendances")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Westmarchestool.Core.Entities.Session", "Session")
                        .WithMany("Attendees")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.UserRole", b =>
                {
                    b.HasOne("Westmarchestool.Core.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Westmarchestool.Core.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Westmarchestool.HexMap.Entities.ConflictVote", b =>
                {
                    b.HasOne("Westmarchestool.HexMap.Entities.MapConflict", "Conflict")
                        .WithMany("Votes")
                        .HasForeignKey("ConflictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Westmarchestool.Core.Entities.User", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conflict");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Westmarchestool.HexMap.Entities.Expedition", b =>
                {
                    b.HasOne("Westmarchestool.Core.Entities.User", "LeaderPlayer")
                        .WithMany()
                        .HasForeignKey("LeaderPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LeaderPlayer");
                });

            modelBuilder.Entity("Westmarchestool.HexMap.Entities.ExpeditionHex", b =>
                {
                    b.HasOne("Westmarchestool.HexMap.Entities.Expedition", "Expedition")
                        .WithMany("ExploredHexes")
                        .HasForeignKey("ExpeditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expedition");
                });

            modelBuilder.Entity("Westmarchestool.HexMap.Entities.ExpeditionMember", b =>
                {
                    b.HasOne("Westmarchestool.Core.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Westmarchestool.HexMap.Entities.Expedition", "Expedition")
                        .WithMany("Members")
                        .HasForeignKey("ExpeditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Westmarchestool.Core.Entities.User", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Expedition");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Westmarchestool.HexMap.Entities.HexTile", b =>
                {
                    b.HasOne("Westmarchestool.HexMap.Entities.Expedition", "DiscoveredByExpedition")
                        .WithMany()
                        .HasForeignKey("DiscoveredByExpeditionId");

                    b.Navigation("DiscoveredByExpedition");
                });

            modelBuilder.Entity("Westmarchestool.HexMap.Entities.MapConflict", b =>
                {
                    b.HasOne("Westmarchestool.Core.Entities.User", "ExistingSubmitter")
                        .WithMany()
                        .HasForeignKey("ExistingSubmitterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Westmarchestool.Core.Entities.User", "NewSubmitter")
                        .WithMany()
                        .HasForeignKey("NewSubmitterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Westmarchestool.HexMap.Entities.TownMapSubmission", "Submission")
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExistingSubmitter");

                    b.Navigation("NewSubmitter");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("Westmarchestool.HexMap.Entities.TownMapSubmission", b =>
                {
                    b.HasOne("Westmarchestool.HexMap.Entities.Expedition", "Expedition")
                        .WithMany()
                        .HasForeignKey("ExpeditionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Westmarchestool.Core.Entities.User", "SubmittedByPlayer")
                        .WithMany()
                        .HasForeignKey("SubmittedByPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Expedition");

                    b.Navigation("SubmittedByPlayer");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.Character", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Inventory");

                    b.Navigation("JsonData");

                    b.Navigation("SessionAttendances");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.Session", b =>
                {
                    b.Navigation("Attendees");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Westmarchestool.HexMap.Entities.Expedition", b =>
                {
                    b.Navigation("ExploredHexes");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Westmarchestool.HexMap.Entities.MapConflict", b =>
                {
                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
