// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Westmarchestool.Infrastructure.Data;

#nullable disable

namespace Westmarchestool.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251109141536_InitialHexMapSchema")]
    partial class InitialHexMapSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Westmarchestool.Core.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ancestry")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Background")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CopperPieces")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<int>("GoldPieces")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PlatinumPieces")
                        .HasColumnType("int");

                    b.Property<string>("PortraitUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SilverPieces")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.CharacterHistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ChangeType")
                        .HasColumnType("int");

                    b.Property<int?>("ChangedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OldValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterHistory");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.CharacterInventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AcquiredDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemDataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("ShopTransactionId")
                        .HasColumnType("int");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterInventory");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.CharacterJsonData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ImportedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("JsonContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.ToTable("CharacterJsonData");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.HexMap.Expedition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("LeaderUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("StartQ")
                        .HasColumnType("int");

                    b.Property<int>("StartR")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeaderUserId");

                    b.ToTable("Expeditions");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.HexMap.ExpeditionHex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DiscoveredDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpeditionId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Q")
                        .HasColumnType("int");

                    b.Property<int>("R")
                        .HasColumnType("int");

                    b.Property<int>("Terrain")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpeditionId", "Q", "R")
                        .IsUnique();

                    b.ToTable("ExpeditionHexes");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.HexMap.ExpeditionMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExpeditionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LeftDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PushDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("PushedToTownMap")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpeditionId");

                    b.HasIndex("UserId");

                    b.ToTable("ExpeditionMembers");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.HexMap.GMMapHex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GmNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsManuallySet")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Q")
                        .HasColumnType("int");

                    b.Property<int>("R")
                        .HasColumnType("int");

                    b.Property<int>("Terrain")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Q", "R")
                        .IsUnique();

                    b.ToTable("GMMapHexes");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.HexMap.HexDiscoveryHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DiscoveryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpeditionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsVerification")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ReportedTerrain")
                        .HasColumnType("int");

                    b.Property<int>("TownMapHexId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpeditionId");

                    b.HasIndex("TownMapHexId");

                    b.ToTable("HexDiscoveryHistory");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.HexMap.PointOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("DiscoveredByExpeditionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DiscoveryDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GMMapHexId")
                        .HasColumnType("int");

                    b.Property<bool>("IsLocationVerified")
                        .HasColumnType("bit");

                    b.Property<string>("LoreArticleUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("PlayerKnownQ")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerKnownR")
                        .HasColumnType("int");

                    b.Property<int?>("TownMapHexId")
                        .HasColumnType("int");

                    b.Property<int>("TrueQ")
                        .HasColumnType("int");

                    b.Property<int>("TrueR")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiscoveredByExpeditionId");

                    b.HasIndex("GMMapHexId");

                    b.HasIndex("TownMapHexId");

                    b.ToTable("PointsOfInterest");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.HexMap.TownMapHex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FirstDiscoveredDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastVerifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Q")
                        .HasColumnType("int");

                    b.Property<int>("R")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Terrain")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Q", "R")
                        .IsUnique();

                    b.ToTable("TownMapHexes");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Full system access",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Game Master access",
                            Name = "GM"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Player access",
                            Name = "Player"
                        });
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExperienceReward")
                        .HasColumnType("int");

                    b.Property<int>("GameMasterUserId")
                        .HasColumnType("int");

                    b.Property<int>("GoldReward")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameMasterUserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.SessionAttendee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attended")
                        .HasColumnType("bit");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("ExperienceReceived")
                        .HasColumnType("int");

                    b.Property<int>("GoldReceived")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RewardsDistributedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SignedUpDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("SessionId");

                    b.ToTable("SessionAttendees");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.Character", b =>
                {
                    b.HasOne("Westmarchestool.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.CharacterHistoryEntry", b =>
                {
                    b.HasOne("Westmarchestool.Core.Entities.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId");

                    b.HasOne("Westmarchestool.Core.Entities.Character", "Character")
                        .WithMany("History")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.CharacterInventoryItem", b =>
                {
                    b.HasOne("Westmarchestool.Core.Entities.Character", "Character")
                        .WithMany("Inventory")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.CharacterJsonData", b =>
                {
                    b.HasOne("Westmarchestool.Core.Entities.Character", "Character")
                        .WithOne("JsonData")
                        .HasForeignKey("Westmarchestool.Core.Entities.CharacterJsonData", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.HexMap.Expedition", b =>
                {
                    b.HasOne("Westmarchestool.Core.Entities.User", "Leader")
                        .WithMany()
                        .HasForeignKey("LeaderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Leader");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.HexMap.ExpeditionHex", b =>
                {
                    b.HasOne("Westmarchestool.Core.Entities.HexMap.Expedition", "Expedition")
                        .WithMany("Hexes")
                        .HasForeignKey("ExpeditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expedition");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.HexMap.ExpeditionMember", b =>
                {
                    b.HasOne("Westmarchestool.Core.Entities.HexMap.Expedition", "Expedition")
                        .WithMany("Members")
                        .HasForeignKey("ExpeditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Westmarchestool.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Expedition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.HexMap.HexDiscoveryHistory", b =>
                {
                    b.HasOne("Westmarchestool.Core.Entities.HexMap.Expedition", "Expedition")
                        .WithMany()
                        .HasForeignKey("ExpeditionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Westmarchestool.Core.Entities.HexMap.TownMapHex", "TownMapHex")
                        .WithMany("DiscoveryHistory")
                        .HasForeignKey("TownMapHexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expedition");

                    b.Navigation("TownMapHex");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.HexMap.PointOfInterest", b =>
                {
                    b.HasOne("Westmarchestool.Core.Entities.HexMap.Expedition", "DiscoveredByExpedition")
                        .WithMany()
                        .HasForeignKey("DiscoveredByExpeditionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Westmarchestool.Core.Entities.HexMap.GMMapHex", "GMMapHex")
                        .WithMany("PointsOfInterest")
                        .HasForeignKey("GMMapHexId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Westmarchestool.Core.Entities.HexMap.TownMapHex", "TownMapHex")
                        .WithMany("PointsOfInterest")
                        .HasForeignKey("TownMapHexId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DiscoveredByExpedition");

                    b.Navigation("GMMapHex");

                    b.Navigation("TownMapHex");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.Session", b =>
                {
                    b.HasOne("Westmarchestool.Core.Entities.User", "GameMaster")
                        .WithMany()
                        .HasForeignKey("GameMasterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameMaster");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.SessionAttendee", b =>
                {
                    b.HasOne("Westmarchestool.Core.Entities.Character", "Character")
                        .WithMany("SessionAttendances")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Westmarchestool.Core.Entities.Session", "Session")
                        .WithMany("Attendees")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.UserRole", b =>
                {
                    b.HasOne("Westmarchestool.Core.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Westmarchestool.Core.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.Character", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Inventory");

                    b.Navigation("JsonData");

                    b.Navigation("SessionAttendances");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.HexMap.Expedition", b =>
                {
                    b.Navigation("Hexes");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.HexMap.GMMapHex", b =>
                {
                    b.Navigation("PointsOfInterest");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.HexMap.TownMapHex", b =>
                {
                    b.Navigation("DiscoveryHistory");

                    b.Navigation("PointsOfInterest");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.Session", b =>
                {
                    b.Navigation("Attendees");
                });

            modelBuilder.Entity("Westmarchestool.Core.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
